### Create Shorten URL with random alias
POST http://localhost:8080/shortener?url=http://www.bemobi.com.br

### Create Shorten URL with custom alias
POST http://localhost:8080/shortener?url=http://www.bemobi.com.br&alias=test12

### Retrieve URL by alias
GET http://localhost:8080/shortener/awbsedf
